name: Deploy to Cloudflare
on:
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy worker
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
